### ISSUE TITLE
TypeError: Cannot read property 'sizeScale' of undefined

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sugar-and-salt-solutions#21]
```
TypeError: Cannot read property 'sizeScale' of undefined
    at Nitrogen.SphericalParticle [as constructor] (http://192.168.0.2:8080/sugar-and-salt-solutions/js/common/model/sphericalparticles/SphericalParticle.js?bust=1447097528259:26:97)
    at new Nitrogen (http://192.168.0.2:8080/sugar-and-salt-solutions/js/common/model/sphericalparticles/Nitrogen.js?bust=1447097528259:30:23)
    at http://192.168.0.2:8080/sugar-and-salt-solutions/js/micro/model/sodiumnitrate/SodiumNitrateConstants.js?bust=1447097528259:17:35
    at Object.context.execCb (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1113:20)
    at http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:132:17
    at http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1156:11
    at each (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:57:23)
    at Object.Module.emit (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1155:9)
```

**Comment by KatieWoe** [comment]
Closing for https://github.com/phetsims/qa/issues/832 as this sim is not viewed by CT anymore. If this is in error feel free to close.
