### ISSUE TITLE
Uncaught TypeError: window.phetSplashScreenDownloadComplete is not a function

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sugar-and-salt-solutions#28]
Caught  with test-server:

```
Uncaught TypeError: window.phetSplashScreenDownloadComplete is not a function
TypeError: window.phetSplashScreenDownloadComplete is not a function
    at new Sim (http://localhost:8080/joist/js/Sim.js?bust=1513027732832:77:12)
    at http://localhost:8080/sugar-and-salt-solutions/js/sugar-and-salt-solutions-main.js?bust=1513027732832:33:15
    at window.phetLaunchSimulation (http://localhost:8080/joist/js/SimLauncher.js?bust=1513027732832:47:11)
    at doneLoadingImages (http://localhost:8080/joist/js/SimLauncher.js?bust=1513027732832:69:18)
    at Object.launch (http://localhost:8080/joist/js/SimLauncher.js?bust=1513027732832:123:9)
    at http://localhost:8080/sugar-and-salt-solutions/js/sugar-and-salt-solutions-main.js?bust=1513027732832:32:15
    at Object.execCb (http://localhost:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (http://localhost:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Module. (http://localhost:8080/sherpa/lib/require-2.1.11.js:1113:20)
    at http://localhost:8080/sherpa/lib/require-2.1.11.js:132:17
```

**Comment by samreid** [comment]
Fixed in a commit earlier today.
